blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
  path('', views.PostsListView.as_view(), name='posts_list'),
  re_path(r'^post/(?P<pk>\d+)$', views.PostDetail.as_view(), name='post_detail'),
  path('post/new', views.CreatePostView.as_view(), name='create_post'),
  re_path(r'^post/(?P<pk>\d+)/edit$', views.UpdatePostView.as_view(), name='update_post'),
  re_path(r'^post/(?P<pk>\d+)/remove$', views.DeletePostView.as_view(), name='remove_post'),
  path('drafts', views.DraftsListView.as_view(), name='drafts'),
  re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
  re_path(r'^comments/(?P<pk>\d+)/approve$', views.approve_comment, name='approve_comment'),
  re_path(r'^comments/(?P<pk>\d+)/remove$', views.remove_comment, name='remove_comment'),
  re_path(r'^post/(?P<pk>\d+)/publish$', views.publish_post, name='publish_post'),
  path('about', views.AboutView.as_view(), name='about'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':''}),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
  author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  text = models.TextField()
  created = models.DateTimeField(default=timezone.now())
  published = models.DateTimeField(blank=True,null=True)

  def publish(self):
    self.published = timezone.now()
    self.save()

  def approved_comments(self):
    return self.comments.filter(approved=True)

  def get_absolute_url(self):
    return reverse('blog:post_detail', kwargs={'pk':self.pk})

  def __str__(self):
      return self.title

class Comment(models.Model):
  post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
  author = models.CharField(max_length=200)
  text = models.TextField()
  created = models.DateTimeField(default=timezone.now())
  approved = models.BooleanField(default=False)

  def approve(self):
    self.approved = True
    self.save()

  def get_absolute_url(self):
    return reverse('blog:post_detail', kwargs={'pk':self.post.pk})

  def __str__(self):
    return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment

class PostForm(forms.ModelForm):

  class Meta:
    model = Post
    fields = ('author', 'title', 'text')

    widgets = {
      'title': forms.TextInput(attrs={'class':'textinputclass'}),
      'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
    }


class CommentForm(forms.ModelForm):

  class Meta:
    model = Comment
    fields = ('author', 'text')

    widgets = {
      'author': forms.TextInput(attrs={'class':'textinputclass'}),
      'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
    }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm

# Create your views here.
class AboutView(TemplateView):
  template_name = 'blog/about.html'

class PostsListView(ListView):
  model = Post
  template_name = 'blog/posts_list.html'
  context_object_name = 'posts'

  def get_queryset(self):
    return Post.objects.filter(published__lte=timezone.now()).order_by('-published')


class PostDetail(DetailView):
  model = Post


class CreatePostView(CreateView, LoginRequiredMixin):
  login_url = '/login/'
  redirect_field_name = 'blog/post_detail.html'
  form_class = PostForm
  model = Post


class UpdatePostView(UpdateView, LoginRequiredMixin):
  login_url = '/login/'
  redirect_field_name = 'blog/post_detail.html'
  form_class = PostForm
  model = Post


class DeletePostView(DeleteView, LoginRequiredMixin):
  login_url = '/login/'
  redirect_field_name = 'blog/post_detail.html'
  model = Post
  template_name = 'blog/confirm_delete_post.html'

  success_url = reverse_lazy('blog:posts_list')


class DraftsListView(ListView, LoginRequiredMixin):
  login_url = '/login/'
  redirect_field_name = 'blog/post_detail.html'
  model = Post
  template_name = 'blog/posts_list.html'

  context_object_name = 'posts'

  def get_queryset(self):
    return Post.objects.filter(published__isnull=True)


@login_required
def add_comment_to_post(request, pk):
  post = get_object_or_404(Post, pk=pk)

  if request.method == "POST":
    form = CommentForm(request.POST)

    if form.is_valid():
      comment = form.save(commit=False)

      comment.post = post
      comment.save()
      return redirect('blog:post_detail', pk=post.pk)
  else:
    form = CommentForm()

  return render(request, 'blog/comment_form.html', context={'form': form})


@login_required
def approve_comment(request, pk):
  comment = get_object_or_404(Comment, pk=pk)
  comment.approve()

  return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def remove_comment(request, pk):
  comment = get_object_or_404(Comment, pk=pk)
  post_pk = comment.post.pk
  comment.delete()

  return redirect('blog:post_detail', pk=post_pk)


@login_required
def publish_post(request, pk):
  post = get_object_or_404(Post, pk=pk)
  post.publish()

  return redirect('blog:post_detail', pk=post.pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block body_block %}
<h1>About me</h1>
<p>Thanks for checking it out!</p>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Blog</title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


  <!-- medium -->
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">

  <!-- js -->
</head>
<body>
  <!-- navbar -->
  <nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand bigbrand" href="{% url 'blog:posts_list' %}">My Blog</a></li>
        <li><a class="navbar-link" href="{% url 'blog:about' %}">About</a></li>
        <li><a class="navbar-link" href="https://www.github.com">GitHub</a></li>
        <li><a class="navbar-link" href="https://www.linkedin.com">LinkedIn</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li>
            <a class="nav navbar-right" href="{% url 'blog:create_post' %}">New post</a>
          </li>
          <li>
            <a class="nav navbar-right" href="{% url 'blog:drafts' %}">Drafts</a>
          </li>
          <li>
            <a class="nav navbar-right" href="{% url 'logout' %}">Logout</a>
          </li>
          <li>
            <a>Welcome, {{ user.username }}!</a>
          </li>
        {% else %}
          <li><a class="nav navbar-right" href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <!-- content block -->
  <div class="content container">
    <div class="row">
      <div class="col-md-8">
        <div class="blog_post">
          {% block body_block %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>New comment</h1>
  <form class="post-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="save btn btn-default" type="submit">Post comment</button>
  </form>
  <script>
    var editor = new MediumEditor('.editable');
  </script>
{% endblock %}

blog/templates/blog/confirm_delete_post.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}?</p>
    <input class="btn btn-danger" type="submit" value="Delete">
  </form>
{% endblock %}

blog/templates/blog/drafts_list.html
{% extends 'blog/base.html' %}

{% block body_block %}
  {% for post in posts %}
    <div class="post">
      <p class="date">Created: {{ post.date|date:"d-m-Y' }}</p>
      <h1><a href="{% url 'post_detail' pk=post.pk }}">{{ post.title }}</a></h1>
      <p>{{ post.text|truncatechars:200 }}</p>
    </div>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1 class="posttitle">{{ post.title }}</h1>
  {% if post.published %}
    <div class="date postdate">{{ post.published }}</div>
  {% else %}
    <div class="btn btn-default"><a href="{% url 'blog:publish_post' pk=post.pk %}">Publish</a></div>
  {% endif %}

  <p class="postcontent">
    {{ post.text|safe|linebreaksbr }}
  </p>
  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:update_post' pk=post.pk %}">
      <span class="glyphicon glyphicon-pencil"></span>
    </a>
    <a class="btn btn-default" href="{% url 'blog:remove_post' pk=post.pk %}">
      <span class="glyphicon glyphicon-remove"></span>
    </a>
  {% endif %}
  
  <hr>

  <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
  <div class="container">
    {% for comment in post.comments.all %}
      <br>
      {% if user.is_authenticated or comment.approved %}
        {{ comment.created }}
          {% if not comment.approved %}
          <a class="btn btn-primary" href="{% url 'blog:approve_comment' pk=comment.pk %}">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <a class="btn btn-default" href="{% url 'blog:remove_comment' pk=comment.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
          </a>
          {% endif %}

          <p>{{ comment.text|safe|linebreaksbr }}</p>

          <p>Posted by {{ comment.author }}</p>
      {% endif %}
      {% empty %}
      <p>No comments!</p>
    {% endfor %}
  </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>New post</h1>
  <form class="post-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="save btn btn-default" type="submit">Save</button>
  </form>

  <script>
    var editor = new MediumEditor(".editable");
  </script>
{% endblock %}

blog/templates/blog/posts_list.html
{% extends 'blog/base.html' %}

{% block body_block %}
<div class="centerstage">
  {% for post in posts %}
    <div class="post">
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
      <div class="date">
        <p>Published on: {{ post.published|date:"D M Y" }}</p>
      </div>
      <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
    </div>
  {% endfor %}
</div>
{% endblock %}